/**
 * Apply pending Drizzle migrations at startup.
 *
 * Migration SQL lives in ./drizzle (generated by `npm run db:generate`).
 * This runs on every boot and is a safe no-op once everything is applied, so
 * deploys don't need a separate migration step. Set MIGRATE_ON_BOOT=false to
 * skip it (e.g. if you run `npm run db:migrate` as a separate deploy hook).
 */
import fs from "fs";
import path from "path";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";

function connectionConfig() {
  const connectionString = process.env.DATABASE_URL;
  if (connectionString) {
    const wantsSsl =
      process.env.DATABASE_SSL === "true" ||
      /[?&]sslmode=(require|verify-ca|verify-full)/.test(connectionString);
    return { connectionString, ssl: wantsSsl ? { rejectUnauthorized: false } : undefined };
  }
  return {
    host: process.env.SQL_HOST,
    port: process.env.SQL_PORT ? Number(process.env.SQL_PORT) : undefined,
    user: process.env.SQL_USER,
    password: process.env.SQL_PASSWORD,
    database: process.env.SQL_DB_NAME,
    ssl: process.env.DATABASE_SSL === "true" ? { rejectUnauthorized: false } : undefined,
  };
}

export async function runMigrations() {
  if (process.env.MIGRATE_ON_BOOT === "false") {
    console.log("[migrate] MIGRATE_ON_BOOT=false - skipping.");
    return;
  }

  const folder = path.resolve(process.cwd(), "drizzle");
  if (!fs.existsSync(folder) || fs.readdirSync(folder).filter((f) => f.endsWith(".sql")).length === 0) {
    console.warn(
      "[migrate] no ./drizzle migrations found - skipping. " +
        "Generate them with `npm run db:generate` (and commit the folder)."
    );
    return;
  }

  const pool = new Pool({ ...connectionConfig(), max: 2, connectionTimeoutMillis: 15000 });
  try {
    const db = drizzle(pool);
    console.log("[migrate] applying migrations from ./drizzle ...");
    await migrate(db, { migrationsFolder: folder });
    console.log("[migrate] database is up to date.");
  } catch (err: any) {
    console.error("[migrate] FAILED:", err.message || err);
    throw err;
  } finally {
    await pool.end().catch(() => {});
  }
}

// Allow running standalone: `npm run db:migrate` (tsx src/db/migrate.ts)
if (process.argv[1]?.replace(/\\/g, "/").endsWith("src/db/migrate.ts")) {
  void (async () => {
    const { assertCoreEnv } = await import("../config/env.ts");
    assertCoreEnv();
    try {
      await runMigrations();
      process.exit(0);
    } catch {
      process.exit(1);
    }
  })();
}
